# Site settings
title: Pixel Ninjas
email: minecraft_freak@pixelninjas.us
description: > # this means to ignore newlines until "baseurl:"
    This is Minecraft Freak's awesome Minecraft blog!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pixelninjas.us" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  pixelninjas

# Build settings
markdown: kramdown
